### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by gh2k** [chef-cookbooks/subversion#21]
I've tried running tests with Ruby 1.9 and 2.1. After running `bundle exec rspec` I get the following output:

```
Celluloid 0.17.1.1 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
Called 'load' without the :safe option -- defaulting to safe mode.
You can avoid this warning in the future by setting the SafeYAML::OPTIONS[:default_mode] option (to :safe or :unsafe).

/home/simon/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:800:in `connect': SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol (Faraday::Error::ConnectionFailed)
	from /home/simon/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:800:in `block in connect'
	from /home/simon/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
	from /home/simon/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
	from /home/simon/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:800:in `connect'
	from /home/simon/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
	from /home/simon/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:745:in `start'
	from /home/simon/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1285:in `request'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
	from /home/simon/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1027:in `get'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.8.9/lib/faraday/adapter/net_http.rb:73:in `perform_request'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.8.9/lib/faraday/adapter/net_http.rb:38:in `call'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/ridley-1.7.1/lib/ridley/middleware/retry.rb:29:in `call'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/ridley-1.7.1/lib/ridley/middleware/follow_redirects.rb:67:in `perform_with_redirection'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/ridley-1.7.1/lib/ridley/middleware/follow_redirects.rb:60:in `call'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.8.9/lib/faraday/response.rb:8:in `call'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.8.9/lib/faraday/connection.rb:253:in `run_request'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.8.9/lib/faraday/connection.rb:106:in `get'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/community_rest.rb:142:in `versions'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/community_rest.rb:161:in `satisfy'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/locations/site_location.rb:66:in `target_version'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/locations/site_location.rb:41:in `download'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/downloader.rb:120:in `download_location'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/downloader.rb:89:in `block in download'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/downloader.rb:85:in `each'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/downloader.rb:85:in `download'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/resolver.rb:137:in `install_source'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/resolver.rb:57:in `add_source'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/resolver.rb:30:in `block in initialize'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/resolver.rb:29:in `each'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/resolver.rb:29:in `initialize'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/berksfile.rb:676:in `new'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/berksfile.rb:676:in `resolve'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/berkshelf-2.0.18/lib/berkshelf/berksfile.rb:418:in `install'
	from /home/simon/code/cookbooks/subversion/spec/spec_helper.rb:8:in `block in <top (required)>'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/thor-0.18.1/lib/thor/shell/basic.rb:19:in `mute'
	from /home/simon/code/cookbooks/subversion/spec/spec_helper.rb:7:in `<top (required)>'
	from /home/simon/code/cookbooks/subversion/spec/unit/recipes/client_spec.rb:1:in `require'
	from /home/simon/code/cookbooks/subversion/spec/unit/recipes/client_spec.rb:1:in `<top (required)>'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `block in load_spec_files'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `each'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load_spec_files'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:18:in `run'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:103:in `run'
	from /home/simon/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:17:in `block in autorun'
```

If I comment the last 3 lines of spec_helper.rb (the Berkshelf stuff, which it appears is causing the above) then I am told:

```
Celluloid 0.17.1.1 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
Called 'load' without the :safe option -- defaulting to safe mode.
You can avoid this warning in the future by setting the SafeYAML::OPTIONS[:default_mode] option (to :safe or :unsafe).

FFFFFFFFF

Failures:

  1) subversion::client on Windows installs Subversion
     Failure/Error: let(:chef_run) { ChefSpec::ChefRunner.new(platform: 'windows', version: '2008R2').converge(described_recipe) }
     NoMethodError:
       undefined method `on_create' for Chef::Cookbook::FileVendor:Class
     # ./spec/unit/recipes/client_spec.rb:5:in `new'
     # ./spec/unit/recipes/client_spec.rb:5:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/client_spec.rb:8:in `block (3 levels) in <top (required)>'

  2) subversion::client on Windows sets the path
     Failure/Error: let(:chef_run) { ChefSpec::ChefRunner.new(platform: 'windows', version: '2008R2').converge(described_recipe) }
     NoMethodError:
       undefined method `on_create' for Chef::Cookbook::FileVendor:Class
     # ./spec/unit/recipes/client_spec.rb:5:in `new'
     # ./spec/unit/recipes/client_spec.rb:5:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/client_spec.rb:12:in `block (3 levels) in <top (required)>'

  3) subversion::client on Ubuntu installs subversion
     Failure/Error: let(:chef_run) { ChefSpec::ChefRunner.new(platform: 'ubuntu', version: '12.04').converge(described_recipe) }
     NoMethodError:
       undefined method `on_create' for Chef::Cookbook::FileVendor:Class
     # ./spec/unit/recipes/client_spec.rb:18:in `new'
     # ./spec/unit/recipes/client_spec.rb:18:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/client_spec.rb:21:in `block (3 levels) in <top (required)>'

  4) subversion::client on Ubuntu installs subversion-tools
     Failure/Error: let(:chef_run) { ChefSpec::ChefRunner.new(platform: 'ubuntu', version: '12.04').converge(described_recipe) }
     NoMethodError:
       undefined method `on_create' for Chef::Cookbook::FileVendor:Class
     # ./spec/unit/recipes/client_spec.rb:18:in `new'
     # ./spec/unit/recipes/client_spec.rb:18:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/client_spec.rb:25:in `block (3 levels) in <top (required)>'

  5) subversion::client on Ubuntu installs libsvn-perl
     Failure/Error: let(:chef_run) { ChefSpec::ChefRunner.new(platform: 'ubuntu', version: '12.04').converge(described_recipe) }
     NoMethodError:
       undefined method `on_create' for Chef::Cookbook::FileVendor:Class
     # ./spec/unit/recipes/client_spec.rb:18:in `new'
     # ./spec/unit/recipes/client_spec.rb:18:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/client_spec.rb:29:in `block (3 levels) in <top (required)>'

  6) subversion::default includes the client recipe
     Failure/Error: let(:chef_run) { ChefSpec::ChefRunner.new(platform: 'ubuntu', version: '12.04').converge(described_recipe) }
     NoMethodError:
       undefined method `on_create' for Chef::Cookbook::FileVendor:Class
     # ./spec/unit/recipes/default_spec.rb:4:in `new'
     # ./spec/unit/recipes/default_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/unit/recipes/default_spec.rb:7:in `block (2 levels) in <top (required)>'

  7) subversion::server includes mod_dav_svn
     Failure/Error: let(:chef_run) { ChefSpec::ChefRunner.new(platform: 'ubuntu', version: '12.04').converge(described_recipe) }
     NoMethodError:
       undefined method `on_create' for Chef::Cookbook::FileVendor:Class
     # ./spec/unit/recipes/server_spec.rb:4:in `new'
     # ./spec/unit/recipes/server_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/unit/recipes/server_spec.rb:7:in `block (2 levels) in <top (required)>'

  8) subversion::server includes the client recipe
     Failure/Error: let(:chef_run) { ChefSpec::ChefRunner.new(platform: 'ubuntu', version: '12.04').converge(described_recipe) }
     NoMethodError:
       undefined method `on_create' for Chef::Cookbook::FileVendor:Class
     # ./spec/unit/recipes/server_spec.rb:4:in `new'
     # ./spec/unit/recipes/server_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/unit/recipes/server_spec.rb:11:in `block (2 levels) in <top (required)>'

  9) subversion::server creates the repo_dir
     Failure/Error: let(:chef_run) { ChefSpec::ChefRunner.new(platform: 'ubuntu', version: '12.04').converge(described_recipe) }
     NoMethodError:
       undefined method `on_create' for Chef::Cookbook::FileVendor:Class
     # ./spec/unit/recipes/server_spec.rb:4:in `new'
     # ./spec/unit/recipes/server_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/unit/recipes/server_spec.rb:15:in `block (2 levels) in <top (required)>'

Finished in 0.00416 seconds
9 examples, 9 failures

Failed examples:

rspec ./spec/unit/recipes/client_spec.rb:7 # subversion::client on Windows installs Subversion
rspec ./spec/unit/recipes/client_spec.rb:11 # subversion::client on Windows sets the path
rspec ./spec/unit/recipes/client_spec.rb:20 # subversion::client on Ubuntu installs subversion
rspec ./spec/unit/recipes/client_spec.rb:24 # subversion::client on Ubuntu installs subversion-tools
rspec ./spec/unit/recipes/client_spec.rb:28 # subversion::client on Ubuntu installs libsvn-perl
rspec ./spec/unit/recipes/default_spec.rb:6 # subversion::default includes the client recipe
rspec ./spec/unit/recipes/server_spec.rb:6 # subversion::server includes mod_dav_svn
rspec ./spec/unit/recipes/server_spec.rb:10 # subversion::server includes the client recipe
rspec ./spec/unit/recipes/server_spec.rb:14 # subversion::server creates the repo_dir
```

There's no Gemfile.lock in the repository, so I'm guessing gem versioning issues.

**Comment by tas50** [comment]
Specs are now fixed
